services:

  files-service-db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - files-service_db_data:/var/lib/postgresql/data/

  files-service-web:
    build:
      context: src/
      dockerfile: Dockerfile
      target: prod
    command: sh /code/entrypoint.sh
    volumes:
      - ./src:/code
      - ./store:/store
    env_file:
      - ./.env
    depends_on:
      - files-service-db

  files-service-nginx:
    image: nginx:1.19.2
    depends_on:
      - files-service-web
      - files-service-db
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/

volumes:
  files-service_db_data:
